title: Records
author:
  name: Hwang, SongYi
  email: thddl8930@gmail.com
description: r0sas0ng's security study records

show_excerpts: true # set to true to show excerpts on the homepage
disqus:
  shortname: hsong2-github-io
# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
google_analytics: G-H5SJV8FDXF
minima:
  date_format: "%b %-d, %Y"
  # generate social links in footer
  social_links:
    #twitter: jekyllrb
    github:  hsong2
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    linkedin: songyi-hwang-a2a4291a0
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
#  - about.md
#  - portfolio.md


# Build settings
theme: minima
paginate: 5
paginate_path: "/page/:num/"

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
